//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_semestral_project
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room()
        {
            this.reservation = new ObservableCollection<reservation>();
        }
    
        public int room_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte size { get; set; }
        public Nullable<int> hotel_id { get; set; }
    
        public virtual hotel hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<reservation> reservation { get; set; }
    }
}
